### ISSUE TITLE
Question to configure mantis

### ISSUE THREAD

**Issue by henrikelopez** [matthiasblaesing/netbeans-mantis-integration#1]
Thanks a lot Matthias!
I've managed to install the plugin in NB 7.2.1 successfully!

I just have a question for configure the values from mantis server, I suppose that the next lines have to be:

$g_source_control_notes_view_status = 10;
$g_source_control_set_resolution_to = 20;
$g_source_control_set_status_to     = 80;

Mantis works fine, but en NB send the next message "failed create client - check URL". Could this be because the URL is a subdomain?

**Comment by hkabir** [comment]
I got the error "Fail request - check username/password" , though username and password perfectly ok.

**Comment by matthiasblaesing** [comment]
@hkabir 

1. Please _never_ high-jack foreign issues for your problems, if your are not 100% certain that they are the same.
2. the plugin is provided as is - I don't regularly give support and I'm not paid for this
3. You did give no information about the problem. From the above:

If you encounter further problem please provide the IDE log (at runtime accessible via View->IDE Log) - or follow these directions: http://wiki.netbeans.org/FaqLogMessagesFile
