### ISSUE TITLE
"Issue tracker" not showing in Services tab

### ISSUE THREAD

**Issue by SpyroTEQ** [matthiasblaesing/netbeans-mantis-integration#20]
I have Netbeans 8.0.2 so I installed Mantis for Netbeans 8.0 from http://plugins.netbeans.org/plugin/45919/mantisintegration . Thing is, there is no "Issue Tracker" (nor Mantis) section in my Services tab:

<img src="http://toile.reinom.com/wp-content/uploads/2015/02/issuetracker.png"/>

Where did Mantis go?! Am I missing something to do or more probably, configure?

**Comment by matthiasblaesing** [comment]
Hey SpyroTEQ, two important things:
1. "Issue Trackers" is called "Task Repositories" (sounds nicer, is the same)
2. You need to register you Task Repository - right click on "Task Repositories" and choose "Create task repositories" in the upcoming dialog please choose mantis and insert your credentials.

**Comment by SpyroTEQ** [comment]
... I should never try new plugins when it's passed midnight ! Thanks a lot.
Maybe updating the screenshot on netbeans plugins website would be a good idea?

**Comment by matthiasblaesing** [comment]
Updated the screenshots. Good idea.
