### ISSUE TITLE
"Assigned to" always invalid.

### ISSUE THREAD

**Issue by 23W** [matthiasblaesing/netbeans-mantis-integration#21]
MantisBT: 1.2.19
NetBeans: 8.0.2
1. In IDE NetBeans we are creating new issue and assigning it to some user.
2. Open this issue in NetBeans. Field "Assigned to" does not show assigned user.
3. Reassing issue to this user again, refresh window...and field "Assigned to" is empty again.

**Comment by matthiasblaesing** [comment]
Please check whether users are listed at all (open the combo box - is the user listed there)?

**Comment by matthiasblaesing** [comment]
Should be fixed by:

https://github.com/matthiasblaesing/netbeans-mantis-integration/commit/d1162e567892bcc3040890ee0fe82b5e1e21b9fc

Please test the following pre-release version:

https://github.com/matthiasblaesing/netbeans-mantis-integration/wiki/MantisIntegration-1.2.1-SNAPSHOT.nbm

**Comment by 23W** [comment]
pre-release version works ok, thank you.
