### ISSUE TITLE
settings would be useful

### ISSUE THREAD

**Issue by jerry1970** [matthiasblaesing/netbeans-mantis-integration#22]
With the dark look and feel installed, the editor windows are not looking very well. Either conforming more to the system colours or let the user select colours for elements would be very useful.

The Find Tasks window has sections that use a custom background colour instead of the system background colour but with NB colour text.

The Status column in the list section of the Find Tasks has custom colours (understandably) but with a NB colour for the text this gives some unreadable combinations.

The Task Details window has larger sections with custom background colour, including empty spaces in text areas.

![mantisnetbeans1](https://cloud.githubusercontent.com/assets/5627407/7315775/fae6f668-ea70-11e4-930f-7f2d7f32ab99.png)
![mantisnetbeans2](https://cloud.githubusercontent.com/assets/5627407/7315774/fae61536-ea70-11e4-8edb-df60a3a4df42.png)

**Comment by jerry1970** [comment]
I realize the background colours for the Status column might be the colours set in Mantis. That makes it more difficult. Best solution for the user (me) would be a configurable text colour, but that would mean you'd have to make an interface for the settings. Probably easier would be a text colour calculator: white or black text based on the background colour's brightness.

Two possible formulas that take into account the intensity of screen colours and the way they translate to monochrome values:
brightness = (R*0.299)+(G*0.587)+(B*0.114)
brightness = Sqr((R * R * 0.241) + (G * G * 0.691) + (B * B * 0.068))
Apparently, these result in a value between 0 (dark) and 255 (bright).

**Comment by matthiasblaesing** [comment]
Should be fixed by:

https://github.com/matthiasblaesing/netbeans-mantis-integration/commit/535be45e49f2f72a8f640a4082c0935931514dc8

Please test the following pre-release version:

https://github.com/matthiasblaesing/netbeans-mantis-integration/wiki/MantisIntegration-1.2.1-SNAPSHOT.nbm

**Comment by jerry1970** [comment]
Solved, looking great, thanks!
