### ISSUE TITLE
columns can only be dragged smaller, not larger

### ISSUE THREAD

**Issue by jerry1970** [matthiasblaesing/netbeans-mantis-integration#23]
The ID column in the list section of the Find Tasks window is too narrow. I can resize it but only make it smaller, not wider. We have Mantis IDs of five digits wide (49212) and I see "49.2..." in the column. Leaving out the thousands separator would probably be enough but a resizable column should of course be resizable in two directions, not one.

**Comment by matthiasblaesing** [comment]
Should be fixed by:

https://github.com/matthiasblaesing/netbeans-mantis-integration/commit/ef1c79391d034b0713bc43dad31a0dea9a0cb17c

Please test the following pre-release version:

https://github.com/matthiasblaesing/netbeans-mantis-integration/wiki/MantisIntegration-1.2.1-SNAPSHOT.nbm

**Comment by jerry1970** [comment]
Excellent, thanks!
