### ISSUE TITLE
Schedule Tasks

### ISSUE THREAD

**Issue by bislewl** [matthiasblaesing/netbeans-mantis-integration#24]
I really like the module, it works like a charm. 
One "feature request" would be if somehow there was an integration for scheduling tasks, so I could schedule a task in mantis and it carry into NetBeans

**Comment by matthiasblaesing** [comment]
Good idea! It is doable - currently the schedule information is held locally in an XML file, what I imaging would be to add two configuration options in the repository configuration, that allows choosing between "built-in" and a custom field with appropriate value.

I'll take a look at it.

**Comment by matthiasblaesing** [comment]
Ok - I just pushed an implementation - a nightly build can be found here:

https://github.com/matthiasblaesing/netbeans-mantis-integration/wiki/MantisIntegration-1.3.1-SNAPSHOT.nbm

This version adds configuration to the repository configuration. If you want to switch to server based scheduling you will have to specify custom fields that can be used as backing store for the configuration. The fields need matching type for the target value (schedule date needs to be of type date and schedule length needs to be numeric and has the additional constraint that it needs to be integer).

It would be nice if you could give it a spin.

**Comment by bislewl** [comment]
What should be the name of the custom fields in Mantis?

**Comment by matthiasblaesing** [comment]
Name them however you want (something speaking like 'Schedule' would be appropriate) - the configuration expects to enter the name of the custom field.

**Comment by bislewl** [comment]
Works Great! What is the Schedule Length for? Any suggestions for a scheduling tool for Mantis?

**Comment by matthiasblaesing** [comment]
Good to hear it is working for you. The schedule length theoretically creates a date range in which the issue is scheduled (ranging from schedule date to "schedule date + length"). I'm pretty sure it not currently exposed in the UI, but I may miss something.

With regard to the scheduling tool for mantis: Sorry no idea, I'm actually not a mantis user myself, so I'm happy you tested and found the change satisfactory, but can't help with that question.

**Comment by bislewl** [comment]
ok, thanks. If I come-up with something I'll let you know! Awesome Work!
