### ISSUE TITLE
notice status in mantis should be configurable (pivate or as default public) 

### ISSUE THREAD

**Issue by bestbean** [matthiasblaesing/netbeans-mantis-integration#25]
git commit messages from netbeans shows up as private notices in mantis, team members don't see them.
Status should be  "public", or configurable ( "public" as default).

**Comment by matthiasblaesing** [comment]
I had a look at the mantis source itself and in fact, it is configurable on the server side - from config_defaults_inc.php:

```php
        /**
         * For open source projects it is expected that the notes be public, however,
         * for non-open source it will probably be VS_PRIVATE.
         * @global int $g_source_control_notes_view_status
         */
        $g_source_control_notes_view_status = VS_PRIVATE;
```

So specifiying:

$g_source_control_notes_view_status = VS_PUBLIC;

in config_inc.php should do the trick.

**Comment by bestbean** [comment]
I did'nt considered server side.
Thanks!
