### ISSUE TITLE
Integration of time tracking plugin

### ISSUE THREAD

**Issue by Sh4d0wF1gh7** [matthiasblaesing/netbeans-mantis-integration#27]
Hello
is it possible to integrate the time tracking plugin from mantis?
Greets

**Comment by matthiasblaesing** [comment]
Timetracking is already enabled. I just checked on 1.2.17 - setting $g_time_tracking_enabled to ON is enough. Can you describe what you want to archive?

**Comment by Sh4d0wF1gh7** [comment]
Great. This works.
I uses since years Egroupware, for Project Management, Tasks and also as Tracker.
Do you think it is possible to create a Netbeans Plugin for the Egroupware Tracker also? Its completely written in PHP and MySQL. I have never programmend a Netbeans Plugin, but Web Applications with PHP, JS f.e. Can you give me ressources for the first steps?

**Comment by matthiasblaesing** [comment]
Well I only had a quick look at it and it could be doable - what you will need:
- Find documentation about the API of the applications inside the egroupware system (googling showed that egroupware has an XMLRPC interface and there are mentions of various DAV connectors)
- Implement some sample code as a standalone client (create an issue, read issues, ...)
- Implement a netbeans module exposing the API of egroupware to netbeans

Documentation of the netbeans side:
http://bits.netbeans.org/dev/javadoc/org-netbeans-modules-bugtracking/overview-summary.html

I would have a look at the various existing plugins:
Github: http://plugins.netbeans.org/plugin/57646/github-issues
Backlog: http://plugins.netbeans.org/plugin/56831/backlog
Mantis: http://plugins.netbeans.org/plugin/45919/mantisintegration
Redmine: http://plugins.netbeans.org/plugin/55824/redminenb

Good luck :-)

**Comment by Sh4d0wF1gh7** [comment]
Are you interested to create it? If yes, we can talk about details: info@medialekt.de

**Comment by matthiasblaesing** [comment]
Sorry - I not interested and have no time to take another project in my free time.
