### ISSUE TITLE
Unable to access my mantisbt over an htaccess

### ISSUE THREAD

**Issue by ftripoli** [matthiasblaesing/netbeans-mantis-integration#28]
Hye,
i have installed "**netbeans 8.1**" for php developpement and then add the "**MantisIntegration 1.3**" via Tools -> Plugins.

But when i try configure my connection to my "**Mantisbt 1.2**" i have the following error :
`Failed request - check usernam/password`

---------------------------------------------------------------------------------------------------

for further information see bellow

Site Information :
**MantisBT Version**: 1.2.19
Schema Version: 183

Additionnal Infos :
**Product Version**: NetBeans IDE 8.1 (Build 201510222201)
Updates: NetBeans IDE is updated to version NetBeans 8.1 Patch 1
Java: 1.8.0_60; Java HotSpot(TM) Client VM 25.60-b23
Runtime: Java(TM) SE Runtime Environment 1.8.0_60-b27
System: Windows 10 version 10.0 running on x86; Cp1252; fr_FR (nb)
User directory: C:\Users\*******\AppData\Roaming\NetBeans\8.1
Cache directory: C:\Users\*******\AppData\Local\NetBeans\Cache\8.1

**Comment by matthiasblaesing** [comment]
- Please attach the netbeans messages log (http://wiki.netbeans.org/FaqLogMessagesFile).
- Please explain why you think the error message is wrong.
- Please check the configuration of the mantis installation: https://www.mantisbt.org/manual/admin.config.soap.html

**Comment by ftripoli** [comment]
Here is the netbeans messages log.
[messages.txt](https://github.com/matthiasblaesing/netbeans-mantis-integration/files/437610/messages.txt)

I think it's wrong because i use other IDE (eclipse for instance) with the same mantis, and the htaccess doesn't bother me ; I type the htaccess login and pass then the mantis user information and that's it. In netbeans it can't make it work until i remove the htaccess. Netbeans ask me the htaccess login and password only the first time (see bellow). I checked multiple time that i used the good informations, but after that i try to acces to mantis through MantisIntegration plugins and the error message appears. Then i comment lines in my htacces and without changing anything in metbeans i try to execute a query in find tasks. The query work ! i can see my tasks.

Tanks to take the time to help me.

![netbean-mantis](https://cloud.githubusercontent.com/assets/5056810/17979016/ec931c36-6af8-11e6-8f0c-7b7d96e27b91.png)

**Comment by matthiasblaesing** [comment]
Ok - http basic auth was never supported and I'm surprised if it would work.

To be frank: I never took these approaches seriously. Why on earth do you put http basic auth in front of a system, that is perfectly capable of authentication? I implemented this for redmine and still think this is mostly because the admin does not bother to fix/update his/her system....

I'll have to look into this.

**Comment by matthiasblaesing** [comment]
I pushed the necessary changes to the repository please check the test version:

http://www.doppel-helix.eu/MantisIntegration-1.3.1-SNAPSHOT.nbm

**Comment by matthiasblaesing** [comment]
@ftripoli did you find some tome to test this?

**Comment by ftripoli** [comment]
I used it and everything seems ok now. In certain cases it usefull to have a double authentication system, but i might be wrong on this.

**Comment by matthiasblaesing** [comment]
Thank you for testing, nice timing!

I also did a release so MantisIntegration 1.4 is tagged and build. I also updated the version in the netbeans plugin portal.

**Comment by ftripoli** [comment]
Thanks YOU to the great job you done and you did. Howhever  when i use the tab "Tool -> Plugins" i can't install the new version, it only propose me the 1.3. Is that normal ?

**Comment by matthiasblaesing** [comment]
What you see in the mentioned menu is the update center contents. I published the new version into the netbeans plugin portal:

http://plugins.netbeans.org/plugin/45919/mantisintegration

After that the plugin can manually downloaded and installed - the default update centers only contain "verified" plugins. Verification is done by a small team of trusted users, that check each new version. (You can see this in the "Verifications for NetBeans versions" section). Verification needs to positive votes, the plugin currently has one, after the second is done, the new version is again available from within netbeans.
