### ISSUE TITLE
Netbeans 8.2 not showing Queries?

### ISSUE THREAD

**Issue by cyraid** [matthiasblaesing/netbeans-mantis-integration#31]
Not showing Queries in Netbeans 8.2 anymore? I know the query files are there, and when I create a new one, all my previous queries shows up for that Netbeans session only.. Then when I close and restart Netbeans, it doesn't show the queries anymore?

**Comment by matthiasblaesing** [comment]
I just ran master and queries survived restarts of the development ide and were directly shown. I'm on linux (ubuntu 16.10) with the JDK from the distribution. Please see if you find suspicious entries in the messages log (or provide it here):

http://wiki.netbeans.org/FaqLogMessagesFile

**Comment by cyraid** [comment]
The only thing that could be suspicious is:

> WARNING [org.netbeans.ProxyClassLoader]: Will not load class org.jdesktop.swingx.painter.BusyPainter arbitrarily from one of ModuleCL@676054f4[org.netbeans.libs.swingx] and ModuleCL@4df2ba9e[eu.doppel_helix.netbeans.MantisIntegration] starting from SystemClassLoader[621 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE

**Comment by cyraid** [comment]
Interestingly enough, I just deleted the repository, uninstalled/reinstalled module, and re-added, and it seems they now persist between restarts.. Weird.. Sorry for the trouble?
