### ISSUE TITLE
Note is not added to Mantis upon SVN commit

### ISSUE THREAD

**Issue by pluk77** [matthiasblaesing/netbeans-mantis-integration#32]
I am using Mantis 2.0.0, Netbeans 8.2 and MantisIntegration 1.5

When committing to SVN, one can add a note to the task in Mantis, using the 'Add details to commit message and task' option. The note however is not added to the task as Mantis has removed a function from the API which seems to be used by the plugin. The following error appears in the apache logs after trying to add a note to the task: 

>  PHP Fatal error:  Function 'mc_issue_checkin' doesn't exist in /srv/www/mantisbt-2.0.0/api/soap/mantisconnect.php on line 84

There is an issue logged on Mantis to remove the function from the WSDL or return an error when it is called. https://www.mantisbt.org/bugs/view.php?id=21291

**Comment by matthiasblaesing** [comment]
Thanks for the heads up. I did a first implementation locally that adds these changes:

- repository configuration gains two new field: values for resolution and status can be choosen
- the commit functions are modified to do two thinks: addNote + update resolution and status

This should do it. I'll post a testversion here in the next few days. The drawback is: While this makes the plugin more flexible (and is required for Mantis 2), other users are forced to modify their configuration.

**Comment by matthiasblaesing** [comment]
Ok - I pushed the change and build a test version - please have a look at this:

https://github.com/matthiasblaesing/netbeans-mantis-integration/wiki/MantisIntegration-1.5.1-SNAPSHOT.nbm

**Comment by matthiasblaesing** [comment]
Any results from testing?

**Comment by pluk77** [comment]
Sorry for the long delay, but thanks a lot for the update. We did limited testing and it seems to work. The note is added to Mantis including the revision. if we come across any problems I will report them back to you.

**Comment by matthiasblaesing** [comment]
Thank you for testing. I'm releasing 1.6 just now.
