### ISSUE TITLE
Version 1.6 not filtering based on 'resolution'

### ISSUE THREAD

**Issue by cyraid** [matthiasblaesing/netbeans-mantis-integration#33]
Hi again! It seems based on my query that has worked with every other version, is now being ignored (_resolution: open_) with the newest version (_1.6?_), and mantis (_2.2.1_).

So in essence, it's showing all the tasks I have, open or not (_lots of strike'd out tasks!_)

**Comment by matthiasblaesing** [comment]
This is not reproducible. Could you make a screenshot of your query. This is what I tested:

![auswahl_001](https://cloud.githubusercontent.com/assets/2179736/24060565/1daf30ec-0b54-11e7-88f0-f63df9d53069.png)

ID 1 has resolution "reopened"
ID 2 has resolution "open"

![auswahl_002](https://cloud.githubusercontent.com/assets/2179736/24060591/4322873e-0b54-11e7-9cf4-25d7d899ed52.png)

The list does not contain the reopened one.

**Comment by cyraid** [comment]
From Mantis on the site (_lists 9, as those are the ones open, filter used is resolution:open_):
![mantiswebsitescreenie](https://cloud.githubusercontent.com/assets/7562753/24069868/920ddc00-0b80-11e7-80a8-eff5562b69be.png)

From Netbeans (_using resolution:open, and assigned by me, same without assigned_):
![netbeansscreenie](https://cloud.githubusercontent.com/assets/7562753/24069869/94894c3a-0b80-11e7-9bd7-e6ddee13ecce.png)

Hope that helps!

**Comment by matthiasblaesing** [comment]
I think I know the reason:

https://github.com/matthiasblaesing/netbeans-mantis-integration/issues/26

You are filtering over resolution, not status! And with issue #26 the default filter of Mantis for the status field went away. Use a status filter and you should be good.

**Comment by cyraid** [comment]
Ahhh.. Yes, the closed hide status probably has something to do with it.. I wanted something that is everything but closed/resolved (_hence, resolution:open_).

Because it works on the site with "resolution:open", I tried saving the filter on the site, and used the handy-dandy filter you have in the Edit Query Tab, and it works great!

Here's what the filter looks like on the site:
![webscreenie2](https://cloud.githubusercontent.com/assets/7562753/24070586/7627a8e6-0b8e-11e7-942a-83cfee905ccb.png)

**Comment by matthiasblaesing** [comment]
Good to here. Can this be closed then?
