### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by lcsqlpete** [matthiasblaesing/netbeans-mantis-integration#34]
I'd love to use this plugin but can't find any documentation as to how it's supposed to work.  Is there any?

Also, it claims to be available on the NetBeans Plugin Portal but it is not listed on the Available tab when I open Tools | Plugins in NetBeans

**Comment by matthiasblaesing** [comment]
This plugin is an integration of mantis into the netbeans issue handling infrastructure. So there is no separate documentation. You install the plugin and after that the netbeans integrations can be used with mantis.

**Comment by lcsqlpete** [comment]
I've installed it into NetBeans but don't see anything different in my
project and no mention of Mantis in any of the NetBeans menus so don;t know
how to make use of the integration.  I'm still not clear as to exactly what
features the integration provides. The plugin sounds useful and I'd like to
use it but right now I'm stuck.
Thanks
Pete

**Comment by matthiasblaesing** [comment]
See the document from netbeans here:

https://netbeans.org/kb/73/ide/kenai-issuetracking.html

**Comment by lcsqlpete** [comment]
Thanks I figured it out after reading another issue.  The NetBeans docs are out of date, mentioning "Issue Tracker" in the Services tab but it should be "Task Repositories.  Up and running now, looks good.
