### ISSUE TITLE
Plugin Stopped Working

### ISSUE THREAD

**Issue by lcsqlpete** [matthiasblaesing/netbeans-mantis-integration#35]
I successfully set this up last week and was able to display data from Mantis within Netbeans.  A couple of days ago a new version of Mantis was installed (2.4.1, Schema version 209) and since then I have not been able to access Mantis.  For example, If I go to the Find page, none of the menus are populated and typing in a report number and clicking Find does not return any data.  There are no error messages.

Also, the name of my Task Repository is greyed out in the dropdown menu which I don;t think used to happen.

Are there any logs anywhere I can search to get more information?

Pete

**Comment by matthiasblaesing** [comment]
I can guess or you can check the message log:

http://wiki.netbeans.org/FaqLogMessagesFile

**Comment by lcsqlpete** [comment]
Thanks.  The message log shows a 404 error but the url is exactly the same as I enter in my browser.  I also get an error in the nb Task Repository Edit window when I click the Check button, this time suggesting I check user name/password but they also have not changed.

I'll check with the Mantis admin person, pretty sure something in the latest release broke something.
